from fastapi import FastAPI, UploadFile, File
from fastapi.responses import JSONResponse, Response
# removed unused/incorrect imports
from analyzer import analyze_logs
import os
import sqlite3

from database import create_db
from utils.helpers import extract_severity

from rag.retriever import search_logs
from rag.embeddings import get_embedding
from rag.vector_store import add_document
from rag.vector_store import documents

from prometheus_client import (
    Counter,
    Histogram,
    generate_latest
)

REQUEST_COUNT = Counter(
    "api_requests_total",
    "Total API Requests"
)

LOGS_ANALYZED = Counter(
    "logs_analyzed_total",
    "Total Logs Analysed"
)

CHAT_REQUESTS = Counter(
    "chat_requests_total",
    "Total AI Chat Requests"
)

ERROR_COUNT = Counter(
    "detected_errors_total",
    "Total Errors Detected"
)

REQUEST_TIME = Histogram(
    "api_request_duration_seconds",
    "API Request Duration"
)

def save_incident(filename, severity, root_cause, recommendation):

    conn = sqlite3.connect("logs.db")

    cursor = conn.cursor()

    cursor.execute("""
    INSERT INTO incidents(
        filename,
        severity,
        root_cause,
        recommendation
    )
    VALUES(?,?,?,?)
    """,(
        filename,
        severity,
        root_cause,
        recommendation
    ))

    conn.commit()
    conn.close()
create_db()

app = FastAPI()

@app.get("/debug-rag")
def debug_rag():
    return {
        "count": len(documents),
        "sample": documents[:3]
    }
    



UPLOAD_DIR = "uploads"
os.makedirs(UPLOAD_DIR, exist_ok=True)


@app.get("/")
def home():

    REQUEST_COUNT.inc()

    return {
        "message": "AI DevOps Copilot Running"
    }

@app.post("/upload-log")
async def upload_log(file: UploadFile = File(...)):
    filepath = os.path.join(UPLOAD_DIR, file.filename or "unknown")

    with open(filepath, "wb") as f:
        content = await file.read()
        f.write(content)

    return {
        "filename": file.filename,
        "status": "uploaded successfully"
    }

@app.get("/history")
def get_history():
    REQUEST_COUNT.inc()

    conn = sqlite3.connect("logs.db")

    cursor = conn.cursor()

    cursor.execute("""
    SELECT *
    FROM incidents
    ORDER BY id DESC
    """)

    rows = cursor.fetchall()

    conn.close()

    return rows

@app.get("/summary")
def get_summary():
    REQUEST_COUNT.inc()

    conn = sqlite3.connect("logs.db")

    cursor = conn.cursor()

    cursor.execute("""
    SELECT root_cause
    FROM incidents
    ORDER BY id DESC
    LIMIT 10
    """)

    rows = cursor.fetchall()

    conn.close()

    text = "\n".join(
        [row[0] for row in rows]
    )

    report = analyze_logs(text)

    return {
        "summary": report
    }

@app.get("/ask")
def ask_logs(question: str):
    REQUEST_COUNT.inc()
    CHAT_REQUESTS.inc()
    try:
        if "count" in question.lower():
            return {
                "answer": f"Total indexed chunks: {len(documents)}"
            }

        results = search_logs(question)

        context = "\n".join(results[:3])
        prompt = f"""
You are an AI assistant.

Use ONLY the retrieved context below.

If the context is not a log file,
answer normally.

If it is a log file,
provide:
- Root Cause
- Impact
- Recommendation

Question:
{question}

Context:
{context}
"""
        answer = analyze_logs(prompt)

        return {
            "question": question,
            "answer": answer,
            "retrieved_logs": results[:3]
        }
    except Exception:
        ERROR_COUNT.inc()
        raise
@app.get("/metrics")
def metrics():
    return Response(
        generate_latest(),
        media_type="text/plain"
    )


@app.post("/analyze-log")
async def analyze_log(file: UploadFile = File(...)):
    REQUEST_COUNT.inc()
    LOGS_ANALYZED.inc()
    content = await file.read()
    try:
        text = content.decode("utf-8")
    except UnicodeDecodeError:
        text = content.decode("latin-1")

    ai_report = analyze_logs(text)
    print("\n========== LOG CONTENT ==========")
    print(text)
    print("=================================\n")
    lines = text.splitlines()

    # chunk and add to vector store
    for i in range(0, len(lines), 50):
        chunk = "\n".join(lines[i:i+50])
        if chunk.strip():
            emb = get_embedding(chunk)
            add_document(chunk, emb)

    severity = extract_severity(ai_report)
    save_incident(
        file.filename,
        severity,
        ai_report[:500],
        "Generated by Llama3"
    )

    errors = []
    warnings = []
    infos = []
    for line in lines:
        if "ERROR" in line:
            errors.append(line)
        elif "WARNING" in line:
            warnings.append(line)
        elif "INFO" in line:
            infos.append(line)

    ERROR_COUNT.inc(len(errors))

    return JSONResponse({
        "summary": {
            "total_lines": len(lines),
            "errors": len(errors),
            "warnings": len(warnings),
            "infos": len(infos)
        },
        "ai_report": ai_report,
        "error_logs": errors[:10],
        "warning_logs": warnings[:10]
    })
    
   