from fastapi import FastAPI, UploadFile, File
from fastapi.responses import JSONResponse
from streamlit import text
from analyzer import analyze_logs
import os
from database import create_db
import sqlite3
from utils import extract_severity




def save_incident(filename, severity, root_cause, recommendation):

    conn = sqlite3.connect("logs.db")

    cursor = conn.cursor()

    cursor.execute("""
    INSERT INTO incidents(
        filename,
        severity,
        root_cause,
        recommendation
    )
    VALUES(?,?,?,?)
    """,(
        filename,
        severity,
        root_cause,
        recommendation
    ))

    conn.commit()
    conn.close()
create_db()

app = FastAPI()

UPLOAD_DIR = "uploads"
os.makedirs(UPLOAD_DIR, exist_ok=True)


@app.get("/")
def home():
    return {"message": "AI DevOps Copilot Running"}


@app.post("/upload-log")
async def upload_log(file: UploadFile = File(...)):
    filepath = os.path.join(UPLOAD_DIR, file.filename or "unknown")

    with open(filepath, "wb") as f:
        content = await file.read()
        f.write(content)

    return {
        "filename": file.filename,
        "status": "uploaded successfully"
    }

@app.get("/history")
def get_history():

    conn = sqlite3.connect("logs.db")

    cursor = conn.cursor()

    cursor.execute("""
    SELECT *
    FROM incidents
    ORDER BY id DESC
    """)

    rows = cursor.fetchall()

    conn.close()

    return rows
@app.get("/summary")
def get_summary():

    conn = sqlite3.connect("logs.db")

    cursor = conn.cursor()

    cursor.execute("""
    SELECT root_cause
    FROM incidents
    ORDER BY id DESC
    LIMIT 10
    """)

    rows = cursor.fetchall()

    conn.close()

    text = "\n".join(
        [row[0] for row in rows]
    )

    report = analyze_logs(text)

    return {
        "summary": report
    }

@app.post("/analyze-log")
async def analyze_log(file: UploadFile = File(...)):
    content = await file.read()
    try:
        text = content.decode("utf-8")
    except UnicodeDecodeError:
        text = content.decode("latin-1")

    ai_report = analyze_logs(text)
    
    severity = extract_severity(ai_report)
    save_incident(
        file.filename,
        severity,
        ai_report[:500],
        "Generated by Llama3"
    )

    lines = text.splitlines()

    errors = []
    warnings = []
    infos = []

    for line in lines:
        if "ERROR" in line:
            errors.append(line)
        elif "WARNING" in line:
            warnings.append(line)
        elif "INFO" in line:
            infos.append(line)

    return JSONResponse({
        "summary": {
            "total_lines": len(lines),
            "errors": len(errors),
            "warnings": len(warnings),
            "infos": len(infos)
        },
        "ai_report": ai_report,
        "error_logs": errors[:10],
        "warning_logs": warnings[:10]
    })